spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    hikari:
      pool-name: sample
